### ISSUE TITLE
[BUG] wrong link in the documentation

### ISSUE THREAD

**Issue by drBenway** [opensearch-project/performance-analyzer#105]
**What is the bug?**
wrong link in the documentation

**How can one reproduce the bug?**
1. Go to [PA/index](https://opensearch.org/docs/latest/monitoring-plugins/pa/index/)
2. Click on 'Download' link in the second paragraph "To download PerfTop, see Download on the OpenSearch website."
3. I nolonger see  the PerfTop download part. I think it got removed with the release to 1.0.0

**What is the expected behavior?**
That I find a download link to perftop on the download page or I direct link under /pa/index

**What is your host/environment?**
 -Not applicable

**Do you have any screenshots?**
Not applicable

**Do you have any additional context?**
Not applicable

**Comment by sruti1312** [comment]
Need to update the documentation to point to release page in perftop repo. 

https://github.com/opensearch-project/perftop/releases/tag/1.2.0.0
