### ISSUE TITLE
[BUG] Flaky org.opensearch.performanceanalyzer.collectors.MasterServiceEventMetricsTests.testCollectMetrics test

### ISSUE THREAD

**Issue by reta** [opensearch-project/performance-analyzer#134]
**What is the bug?**

The `org.opensearch.performanceanalyzer.collectors.MasterServiceEventMetricsTests.testCollectMetrics`seems to be flaky and fails randomly:

```
Suite: Test class org.opensearch.performanceanalyzer.collectors.MasterServiceEventMetricsTests
  2> java.lang.AssertionError
org.opensearch.performanceanalyzer.collectors.MasterServiceEventMetricsTests > testCollectMetrics FAILED
    java.lang.AssertionError
        at org.opensearch.performanceanalyzer.util.TestUtil.readMetricsInJsonString(TestUtil.java:45)
        at org.opensearch.performanceanalyzer.util.TestUtil.readMetricsInJsonString(TestUtil.java:45)
        at org.opensearch.performanceanalyzer.collectors.MasterServiceEventMetricsTests.testCollectMetrics(MasterServiceEventMetricsTests.java:155)
        at org.opensearch.performanceanalyzer.collectors.MasterServiceEventMetricsTests.testCollectMetrics(MasterServiceEventMetricsTests.java:155)
```

**How can one reproduce the bug?**
See please https://github.com/opensearch-project/performance-analyzer/runs/5100788184?check_suite_focus=true

**What is the expected behavior?**
Test should always pass

**What is your host/environment?**
 - Github Actions CI

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
Add any other context about the problem.

**Comment by kkhatua** [comment]
Tests are flaky due to the test verification being a parallel execution path that periodically tries to check if the metrics made it. This does not mean that the test doesn't work, but we need a more deterministic way to verify. Marking this with `Medium` priority and something that would be a good issue for a first timer.

**Comment by khushbr** [comment]
This test has been renamed to [ClusterManagerServiceEventMetricsTests](https://github.com/opensearch-project/performance-analyzer/blob/main/src/test/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceEventMetricsTests.java) and is now successfully running.
