### ISSUE TITLE
[FEATURE] Incremented version to 1.2.5

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/performance-analyzer#135]
Incremented version to 1.2.5 in 1.2 following from https://github.com/opensearch-project/opensearch-build/issues/1600 to prepare for the next possible release.

Backport the change to higher version branches

**Comment by khushbr** [comment]
Closing this issue as we released 1.3.0 (Minor version).

https://github.com/opensearch-project/performance-analyzer/tree/1.3
