### ISSUE TITLE
Enable rollingUpgrade backward compatible test for jdk8

### ISSUE THREAD

**Issue by sgup432** [opensearch-project/performance-analyzer#170]
**Is your feature request related to a problem?**
We had disabled rollingUpgradeTask bwc test specifically for jdk8 as we were seeing issues. 
Related PR where change was done - https://github.com/opensearch-project/performance-analyzer/pull/159

**What solution would you like?**
Enable rollingUpgradeTask bwc test.

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by sruti1312** [comment]
As JDK 8 is not supported from 2.0.0, we can remove the checks and enable the tests for all versions.
