### ISSUE TITLE
[BUG] BWC tests are flaky on Java 11

### ISSUE THREAD

**Issue by sruti1312** [opensearch-project/performance-analyzer#190]
**What is the bug?**
BWC tests are flaky on Java 11
https://github.com/opensearch-project/performance-analyzer/runs/6069211999?check_suite_focus=true

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dblock** [comment]
This seems to have failed in https://github.com/opensearch-project/performance-analyzer/pull/204 again, can we prioritize?

**Comment by Tjofil** [comment]
Currently tests are not even getting run for any type of mixed cluster (combination of bwc version and latest version OS nodes) as there appears to be a problem with the cluster upgrading in multiple OS repos, not just PA. This part has to be reworked and modeled around newer version of build-tools functions from the core, which should solve the test problems as well.
