### ISSUE TITLE
performance-analyzer.log is not rotated

### ISSUE THREAD

**Issue by Kenshir0** [opensearch-project/performance-analyzer#226]
**Describe the bug**
We are running a three node cluster on Docker and our monitoring system reported that the node disks were running out of space. After digging out we have noticed that `/usr/share/opensearch/logs/performance-analyzer.log` was not rotated (the file was huge, several GiB). 

I went through the documentation and found nothing on the subject.

I have to run this command once in a while on each Opensearch node to workaround the issue:
```
docker exec <opensearch_container> truncate -s0 /usr/share/opensearch/logs/performance-analyzer.log
```

**To Reproduce**
1. Deploy an Opensearch on Docker
2. Let it run for a while

**Expected behavior**
`/usr/share/opensearch/logs/performance-analyzer.log` should be rotated

**Plugins**
Security plugin

**Host/Environment:**
 - OS: Debian Bullseye
 - Opensearch Docker image opensearchproject/opensearch:1.2.4
 - Docker CE 20.10.12

**Comment by dblock** [comment]
Moved this to performance-analyzer.

**Comment by Kenshir0** [comment]
Any news on this? Thanks.

**Comment by tuotempo** [comment]
I have the same issue, here is my environment:
**Host/Environment:**

- OS: Ubuntu 18.04.4 LTS
- Opensearch Docker image: opensearchproject/opensearch:1.2.3
- Docker: 20.10.11, build dea9396

can you confirm?
Thanks.

**Comment by sruti1312** [comment]
PA reader or PA-RCA application logs are currently written to ```/usr/share/opensearch/logs/performance-analyzer.log``` and ```/tmp/PerformanceAnalyzer.log```. 

Log rotation is present for ```/tmp``` location but not for the other. Expected behaviour for the application to write logs to only one location, which in this case is ```/tmp``` location.
https://github.com/opensearch-project/performance-analyzer-rca/blob/main/config/log4j2.xml#L7

Will check and remove the setting populating logs to the logs directory.

**Comment by ccottam** [comment]
I believe is the issue is the opensearch-docker-entrypoint.sh file

https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/config/opensearch/opensearch-docker-entrypoint.sh#L112

**Comment by logopk** [comment]
Stadardout, so there is no rotation inside the software.

**Comment by guillaume-alvarez** [comment]
I understand the redirection of console logs to file is an issue in opensearch packaging, however I opened an issue about the flooding logs: #355
