### ISSUE TITLE
Level up README and related markdown content

### ISSUE THREAD

**Issue by dblock** [opensearch-project/performance-analyzer#24]
Level up and cleanup markdown content. 

See [.github#8](https://github.com/opensearch-project/.github/issues/8) for details and recommendations, and [common-utils](https://github.com/opensearch-project/common-utils/) for an example.

- [ ] README.md
- [ ] CONTRIBUTING.md
- [ ] DEVELOPER_GUIDE.md
- [ ] MAINTAINERS.md
- [ ] ADMINS.md
- [ ] SECURITY.md
- [ ] RELEASING.md
- [ ] TESTING.md
- [ ] other .md files

**Comment by sruti1312** [comment]
Merged as a part of this PR: https://github.com/opensearch-project/performance-analyzer/commit/12f934256efc7590352edff5a7f831c740fe0fb4
