### ISSUE TITLE
Bump jackson and snakeyaml dependencie

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/performance-analyzer#288]
**Is your feature request related to a problem?**
Core has bumped jackson and snakeyaml dependencies [here](https://github.com/opensearch-project/OpenSearch/pull/4556) to 2.13.4 and 1.32 respectively for versions 2.x, 2.3 , 2.2 , 2.1 , 2.0, 1.3 and 1.x. Plugin and client teams should do the same to align with core.

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by kkhatua** [comment]
Looks like this has only `jackson` dependencies and not `snakeyaml`.

Also need to bump up the versions in RCA package:
https://github.com/opensearch-project/performance-analyzer-rca/blob/e7570317dad130b1b3fbf9a07726f6edb529ebf8/build.gradle#L318

**Comment by bbarani** [comment]
@kkhatua Has this change merged for 2.4.0 release?

**Comment by kkhatua** [comment]
The change is in for 2.x : 
https://github.com/opensearch-project/performance-analyzer/commit/9b45b551fd94f0792941f9e533fab86e60eef63e
https://github.com/opensearch-project/performance-analyzer-rca/commit/ffeca766b20e100114547d55b594701b38f5fb1b
The 2.x branch also has OS+PA version bumps to 2.4 but the branch isnt cut as yet.
(cc: @kiranprakash154 )
