### ISSUE TITLE
[BUG] Support for HTTP/2 in Ver 3.0.0 is breaking in Performance Analyzer

### ISSUE THREAD

**Issue by kkhatua** [opensearch-project/performance-analyzer#307]
**What is the bug?**
OpenSearch is including support for HTTP/2 (client side) in Ver 3.0.0
That resulted in some breaking changes for classes used by the plugins within the eco-system, one of which is Performance Analyzer.
The following classes are missing in the tests for this repo:
```
RequestConfig
org.apache.http
org.apache.http.auth
org.apache.http.client
org.apache.http.client.config
org.apache.http.conn.ssl
org.apache.http.impl.client
org.apache.http.impl.nio.client
org.apache.http.message
org.apache.http.ssl
org.apache.http.util
```
Ref: https://build.ci.opensearch.org/job/distribution-build-opensearch/6218/console

The changes need to be done for Performance Analyzer are on these lines: https://github.com/opensearch-project/common-utils/pull/281/files

**How can one reproduce the bug?**
Building the distribution fails:
https://build.ci.opensearch.org/job/distribution-build-opensearch/6218/console

**What is the expected behavior?**
Building the distribution should succeed without issue.

**What is your host/environment?**
N/A

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
N.A

**Comment by kaushalmahi12** [comment]
This index [page](https://hc.apache.org/httpcomponents-client-5.1.x/current/httpclient5/apidocs/index-all.html#_H_) lists all the api/class qualified name changes.

**Comment by kkhatua** [comment]
Please check the RCA package for any changes needed there as well.

**Comment by dzane17** [comment]
PA fixed with https://github.com/opensearch-project/performance-analyzer/pull/313.
No `org.apache.http.*` packages used in PA-RCA.
