### ISSUE TITLE
buildRca gradle task only builds main branch of RCA

### ISSUE THREAD

**Issue by mch2** [opensearch-project/performance-analyzer#45]
The buildRca step only clones and builds the main branch of the RCA repo.  This makes it impossible to build tags that require tagged versions of RCA

- https://github.com/opensearch-project/performance-analyzer/blob/main/build.gradle#L324

This could possibly take an optional param to allow overriding main as the default.

**Comment by dblock** [comment]
If you have a dependency on another project, assume that's built and its output is placed into local maven, or its output is copied as part of the build. CI is where one should declare which branch of the dependency to build.

**Comment by dblock** [comment]
Dup of #44?

**Comment by mch2** [comment]
> Dup of #44?

These are different issues.

44 is failing because it is relying on main to be cloned to run spotless.

This issue is around cloning and building the main branch of the RCA repository when building this repository.
