### ISSUE TITLE
[BUG] Circular dependency on performance-analyzer-rca

### ISSUE THREAD

**Issue by sruti1312** [opensearch-project/performance-analyzer#50]
**Is your feature request related to a problem?**
RCA package is built inline. The RCA project needs to build and publish itself in a way that can be picked up by PA, just like all the dependencies and the circular dependency resolved.

Background into this issue:

Currently RCA project is built as a part of PA build followed by unpacking and copying the RCA artifacts to PA artifacts location. Answering to why this is different from other types of dependencies. Inorder to create the PA artifact,i it relies on copying files and folders from the RCA package, we use gradle for building and bring in these RCA bits into PA artifact.
opendistro-for-elasticsearch/performance-analyzer#131
RCA package is more of a component built and shipped along with PA plugin than a dependency. 

**What solution would you like?**
We want to change it in a way that PA consume RCA like a dependency and one of the projects needs to stop depending on the other.

**Additional info**

To increment versions to 1.1 we had to:
in performance-analyzer: #53 that relied on a private branch of performance-analyzer-rc + #54
in performance-analyzer-rc: https://github.com/opensearch-project/performance-analyzer-rca/pull/55 that relied on a private branch + https://github.com/opensearch-project/performance-analyzer-rca/pull/58

**Comment by dblock** [comment]
I think there's more to this: there is a circular dependency between performance-analyzer and performance-analyzer-rca in CI.

- performance-analyzer git clone's performance-analyzer-rca to run its integ tests
- performance-analyzer-rca builds and installs performance-analyzer, enables itself (RCA) and runs integration tests

If both projects stop building each-other, and consume each-other's snapshot builds it will be half the battle.

**Comment by kkhatua** [comment]
@sruti1312  can you provide what would be required to fix this?

**Comment by khushbr** [comment]
This issue is fixed with creation of new library (https://github.com/opensearch-project/performance-analyzer-commons/) to house the common code.
