### ISSUE TITLE
[BUG] Gradlew Build/Assemble failed

### ISSUE THREAD

**Issue by CoderJeffrey** [opensearch-project/performance-analyzer#500]
**What is the bug?**
`./gradlew build ` or` gradlew assemble` for latest version failed 
```
Error Message:
Execution failed for task ':updateShas'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Conflict(s) found for the following module(s):
       - org.apache.logging.log4j:log4j-api between versions 2.20.0 and 2.17.1
       - org.apache.logging.log4j:log4j-core between versions 2.20.0 and 2.17.1
     Run with:
         --scan or
         :dependencyInsight --configuration runtimeClasspath --dependency org.apache.logging.log4j:log4j-api
     to get more insight on how to solve the conflict.
```

**How can one reproduce the bug?**
git clone the main branch package, `./gradlew build`

**What is the expected behavior?**
Build Successful

**Do you have any screenshots?**
![image](https://github.com/opensearch-project/performance-analyzer/assets/60024073/9a2b6aae-392d-49ec-ad6f-551a29ccfa6f)

**Do you have any additional context?**
N/A

**Comment by khushbr** [comment]
Fixed at https://github.com/opensearch-project/performance-analyzer-commons/commit/0197ef09386c5517073a33268db0fc1612e9c1a8
