### ISSUE TITLE
[BUG] ThreadPoolStats constructor undefined

### ISSUE THREAD

**Issue by davidosorno** [opensearch-project/performance-analyzer#552]
**What is the bug?**
ThreadPoolStats constructor is not defined for the number of parameters sent.

**How can one reproduce the bug?**
1. Go to 'ThreadPoolStats' file.
2. Verify 'generateThreadPoolStat(long rejected)' method.
3. See error.

**What is the expected behavior?**
I should be able to create an instance of ThreadPoolStats.

**Do you have any screenshots?**
![Screenshot from 2023-10-02 10-18-23](https://github.com/opensearch-project/performance-analyzer/assets/48450162/2510d329-382e-409d-864c-301e76d9adf3)

**Comment by DesmondWillowbrook** [comment]
Some additional context that may be useful:
While reproducing the bug, the following files are created/deleted according to Git:

```
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .gitignore
        deleted:    licenses/commons-lang3-3.12.0.jar.sha1
        deleted:    licenses/performance-analyzer-commons-1.0.0-SNAPSHOT.jar.sha1

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        licenses/commons-lang3-3.13.0.jar.sha1
        licenses/performance-analyzer-commons-1.1.0-SNAPSHOT.jar.sha1
```
(I appended `/bin/` to `.gitignore` because it would otherwise show 146 untracked files.)

This may point to some sort of version mismatch with respect to other repositories in the OpenSearch project. 

Also here's the command-line output for `./gradlew build` if that may be easier to follow:

```
> Task :compileTestJava FAILED
/home/desmond-lin-7/opensearch/performance-analyzer/src/test/java/org/opensearch/performanceanalyzer/collectors/ThreadPoolMetricsCollectorTests.java:112: error: no suitable constructor found for Stats(String,int,int,int,long,int,int)
        stats.add(new ThreadPoolStats.Stats("write", 0, 0, 0, rejected, 0, 0));
                  ^
    constructor Stats.Stats(String,int,int,int,long,int,long,long) is not applicable
      (actual and formal argument lists differ in length)
    constructor Stats.Stats(StreamInput) is not applicable
      (actual and formal argument lists differ in length)
```

**Comment by khushbr** [comment]
Thank you for flagging this @davidosorno @DesmondWillowbrook


This issue has been fixed at https://github.com/opensearch-project/performance-analyzer/commit/e7713ba05d42453d03ee266ec8f3935a56503603#diff-dc72c254fb47b7933bbde3d7f72e6ffca202762b303f31e063f31cad25823749
