### ISSUE TITLE
Since upgrade from 2.9 to 2.11 I get several warnings "Fail to read queue capacity via reflection" during startup

### ISSUE THREAD

**Issue by thomass4t** [opensearch-project/performance-analyzer#597]
**What is the bug?**
During startup several warnings are logged (37 lines of the same message):
[WARN ][o.o.p.c.ThreadPoolMetricsCollector] [xxx] Fail to read queue capacity via reflection

**How can one reproduce the bug?**

**What is the expected behavior?**
Startup without this warning or at least showing the root cause of the warning

**What is your host/environment?**
 - OS: Ubuntu
 - Version 22.04 LTS

**Do you have any additional context?**
The warnings occured after upgrading opensearch from 2.9 to 2.11

The class ThreadPoolMetricsCollector is logging the warning, but the exception itself is not logged. So, no further information about the deeper lying error is reported.

Maybe the logging can be adjusted to figure out the root cause (if the reason of the warning can't be found)

**Comment by dblock** [comment]
[Triage -- attendees [1](https://github.com/dblock), [2](https://github.com/peternied), [3](https://github.com/reta), [4](https://github.com/krisfreedain), [5](https://github.com/Getsaurabh02), [6](https://github.com/gkamat), [7](https://github.com/scrawfor99)]

Is this still an issue in newer versions @thomass4t?

**Comment by HoffmannTom** [comment]
It seems not to occur in version 2.13.0 any more.

**Comment by thomass4t** [comment]
Sorry.. used my private account before.
It seems not to occur in version 2.13.0 any more.  :)
