### ISSUE TITLE
[BUG] java.lang.IllegalArgumentException: cannot add context to list

### ISSUE THREAD

**Issue by etgraylog** [opensearch-project/performance-analyzer#637]
**What is the bug?**
The `performance-analyzer-agent-cli` generates the following exception during startup in OpenSearch 2.12.0:

```
user@ip-10-1-1-2:~$ sudo systemctl status --full --no-pager opensearch-performance-analyzer
● opensearch-performance-analyzer.service - OpenSearch Performance Analyzer
     Loaded: loaded (/lib/systemd/system/opensearch-performance-analyzer.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2024-03-13 20:54:46 UTC; 9min ago
   Main PID: 1735 (java)
      Tasks: 17 (limit: 9252)
     Memory: 80.3M
     CGroup: /system.slice/opensearch-performance-analyzer.service
             └─1735 /usr/share/opensearch/jdk/bin/java -Xshare:auto -Xms4m -Xmx64m -XX:+UseSerialGC -Dlog4j.configurationFile=/etc/opensearch/opensearch-performance-analyzer/log4j2.xml -Xms64M -Xmx64M -XX:+UseSerialGC -XX:CICompilerCount=1 -XX:-TieredCompilation -XX:InitialCodeCacheSize=4096 -XX:MaxRAM=400m -Dopensearch.path.home=/usr/share/opensearch -Dopensearch.path.conf=/etc/opensearch -Dopensearch.distribution.type=deb -cp /usr/share/opensearch/lib/*:/usr/share/opensearch/performance-analyzer-rca/lib/* org.opensearch.performanceanalyzer.PerformanceAnalyzerApp

Mar 13 20:54:46 ip-10-1-1-2 systemd[1]: Started OpenSearch Performance Analyzer.
Mar 13 20:54:48 ip-10-1-1-2 performance-analyzer-agent-cli[1735]: Exception in thread "main" java.lang.IllegalArgumentException: cannot add context to list
Mar 13 20:54:48 ip-10-1-1-2 performance-analyzer-agent-cli[1735]:         at jdk.httpserver/sun.net.httpserver.ContextList.add(ContextList.java:37)
Mar 13 20:54:48 ip-10-1-1-2 performance-analyzer-agent-cli[1735]:         at jdk.httpserver/sun.net.httpserver.ServerImpl.createContext(ServerImpl.java:276)
Mar 13 20:54:48 ip-10-1-1-2 performance-analyzer-agent-cli[1735]:         at jdk.httpserver/sun.net.httpserver.HttpServerImpl.createContext(HttpServerImpl.java:74)
Mar 13 20:54:48 ip-10-1-1-2 performance-analyzer-agent-cli[1735]:         at jdk.httpserver/sun.net.httpserver.HttpServerImpl.createContext(HttpServerImpl.java:39)
Mar 13 20:54:48 ip-10-1-1-2 performance-analyzer-agent-cli[1735]:         at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.createClientServers(PerformanceAnalyzerApp.java:354)
Mar 13 20:54:48 ip-10-1-1-2 performance-analyzer-agent-cli[1735]:         at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.createClientServers(PerformanceAnalyzerApp.java:319)
Mar 13 20:54:48 ip-10-1-1-2 performance-analyzer-agent-cli[1735]:         at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.main(PerformanceAnalyzerApp.java:112)
user@ip-10-1-1-2:~$
```

**How can one reproduce the bug?**
1. Install OpenSearch 2.12.0 via DEB package on a Debian/Ubuntu host.
2. Evaluate status of the `opensearch-performance-analyzer.service`.

**What is the expected behavior?**
The `opensearch-performance-analyzer.service` (`opensearch-performance-analyzer-cli` process) to start successfully without exception & ultimately respond to HTTP requests sent to its default socket-listener on port 9600.

**What is your host/environment?**
 - OS: Ubuntu 20.0.4.6 LTS
 - Version 2.12.0
 - Plugins
   - Nothing 'extra' was installed, only the plug-ins enabled by default with 2.12.0.

OS: 

**Do you have any screenshots?**
N/A, see output from `systemctl` in Description.

**Do you have any additional context?**
This problem does not seem to exist in versions before 2.12.0 (ex: 2.11.1), as the `opensearch-performance-analyzer.service` functions as expected & is responsive to requests to its default socket-listener on Port 9600 in older versions.

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/krisfreedain) [3](https://github.com/gkamat) [4](https://github.com/andrross) [5](https://github.com/getsaurabh02)

**Comment by etgraylog** [comment]
Closing this as a duplicate of [opensearch-project/performance-analyzer-rca](https://github.com/opensearch-project/performance-analyzer-rca/) issue [#545](https://github.com/opensearch-project/performance-analyzer-rca/issues/545).
