### ISSUE TITLE
Release version 1.2

### ISSUE THREAD

**Issue by dblock** [opensearch-project/performance-analyzer#65]
Coming from [opensearch-build#567](https://github.com/opensearch-project/opensearch-build/issues/567), release version 1.2. Please follow the following checklist.

### Preparation

- [x] Assign this issue to a release owner.
- [x] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] Create, update, triage and label all features and issues targeted for this release with `v1.2.0`.

### CI/CD

- [x] Increment version on main to `1.2.0.0`. (Pull #71 )
- [x] Ensure working and passing CI.
- [x] Re(add) this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).

### Pre-Release

- [x] Branch and build from a `1.2` branch.
- [x] Update your branch in the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).
- [x] Feature complete, pencils down.
- [x] Fix bugs that target this release.

### Release

- [x] Complete [documentation](https://github.com/opensearch-project/documentation-website).
- [x] Gather, review and publish release notes.
- [x] Verify all issued labeled for this release are closed or labelled for the next release.

### Post Release

- [x] Create [a release tag](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#tagging).
- [ ] Suggest improvements to [this template](https://github.com/opensearch-project/opensearch-plugins/templates/release.md).
- [ ] Conduct a postmortem, and publish its results.

**Comment by peternied** [comment]
There is a bundle build break from PA, see https://github.com/opensearch-project/opensearch-build/issues/885

**Comment by peternied** [comment]
@peterzhuamazon found an issue that looks like it was suppose to be resolved in the `v1.2.0` release, please investigate https://github.com/opensearch-project/performance-analyzer/issues/82

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon found an issue that looks like it was suppose to be resolved in the `v1.2.0` release, please investigate #82

Just talked with @sruti1312  and the confusion is cleared up
We dont need to include RCA in manifest as the gradle build action in PA repo will auto checkout RCA and both will be built and bundled into one ZIP.
@sruti1312 will send a PR to remove RCA from the input manifest.
Thanks.

**Comment by kjoseph07** [comment]
The release tags have been published. Any postmortem (retrospective) issues will be added to this [retrospective issue](https://github.com/opensearch-project/opensearch-build/issues/880).
